### ISSUE TITLE
console里面stop后,提示报错

### ISSUE THREAD

**Issue by dfaofeng** [Pai2Chen/mirai-console-addition#2]
![image](https://user-images.githubusercontent.com/14891398/91459923-cd595900-e8b9-11ea-8609-cd3c93b5c756.png)

**Comment by Dreamail** [comment]
这是mirai-console的bug，请等待mirai-console更新或自行修改代码

**Comment by dfaofeng** [comment]
官方已经修复了这个bug了

**Comment by Dreamail** [comment]
自己看源码，，mirai-console在成功disable插件之后抛出异常
