### ISSUE TITLE
登录密码是不支持英文吗?

### ISSUE THREAD

**Issue by GreenChennai** [Pai2Chen/mirai-console-addition#3]
登录密码是不支持英文吗?
MD5密码也不知道怎么获取
是把密码直接转MD5还是有特殊的方式?

**Comment by auqhjjqdo0** [comment]
把你的密码转成MD5 32位的，复制到config的passwd就能用了，百度有MD5转换工具，或者你直接关掉MD5登录就行

**Comment by Dreamail** [comment]
请仔细看README
可以通过命令添加自动登录
